version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pakistan124
      POSTGRES_DB: chatcraftai
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/chatcraftai
      JWT_SECRET: 56789rtyhu876
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:5000

volumes:
  pgdata:
