version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pakistan124
      POSTGRES_DB: chatcraftai
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
